mode = "dark"

accent = "#798186"
#accent = "#98971a"
#accent = "#798186"
#accent = "#ebdbb2"
selection = "#d65d0e"
muted = "#665c54"

background = "#121212"
dark_background = "#0c0e10"
darker_background = "#080a0b"
lighter_background = "#1d2021"

#background = "#141617"
#background = "#121212"
#background = "#101315"
#dark_background = "#1d2021"
#darker_background = "#141617"
#lighter_background = "#282828"
#lighter_background = "#3c3836"

foreground = "#ebdbb2"
dark_foreground = "#7c6f64"
light_foreground = "#d5c4a1"
bright_foreground = "#fbf1c7"

red = "#cc241d"
yellow = "#d79921"
orange = "#d65d0e"
green = "#98971a"
cyan = "#689d6a"
blue = "#458588"
magenta = "#b16286"
brown = "#af3a03"

bright_red = "#fb4934"
bright_yellow = "#fabd2f"
bright_green = "#b8bb26"
bright_cyan = "#8ec07c"
bright_blue = "#83a598"
bright_magenta = "#d3869b"
